# how much damage the turret does per shot
turret-damage: 10

#The turrets health
turret-health: 40.0

#Wether the turret will explode on death
turret-explode: true

#how strong the turrets self explosion will be
turret-explode-strength: 3

# The model name ModelEngine uses to identify the model used
# DO NOT CHANGE THIS IF YOU ARE USING THE DEFAULT TEXTURE PACK
turret-model-name: "turret"