# how much damage the turret does per shot
turret-damage: 10

#The turrets health
turret-health: 40.0

#Wether the turret will explode on death
turret-explode: true

#how strong the turrets self explosion will be
turret-explode-strength: 3f