
############################
#           DRONE          #
############################
# Drones health
drone-health: 40.0

#How long before you can drop another bomb (in ticks)
bomb-cooldown: 80

# How much lower above the model the player will be (compared to default armorstand height)
drone-offset: 1.0

drone-model-name: "drone"




############################
#         TURRET           #
############################

# how much damage the turret does per shot
turret-damage: 10

#The objects health
turret-health: 40.0

#Wether the turret will explode on death
turret-explode: true

#how strong the objects self explosion will be
turret-explode-strength: 3

#How high you can look with a turret
# the values are inverted negative is up positive is down
min-turret-pitch: -19.8

#How low you can look with a turret
max-turret-pitch: 10.0

# How long before the turret can shoot again
turret-cooldown: 2 # in ticks

# ADVANCED SETTINGS
# DO NOT CHANGE THESE UNLESS YOU KNOW WHAT YOU'RE DOING

# The model name ModelEngine uses to identify the model used
turret-model-name: "turret"
# just in case the default value for this is "turret"


#How high the player in spectator mode is placed compared to the main armorstand's height
#KEEP IN MIND : We are talking about a vanilla armorstand here so a bit less than 2 blocks tall
# So if your model is taller than an armorstand for the spectator to be above it, you will have to add rather than subtract
controller-height-offset: -0.7

#How long after the plugin loads do the objects get loaded
# This is to avoid trying to grab a modelEngine model that isn't loaded thus crashing
device-load-delay: 20 #in ticks
# I have found 20 to work nice and stable, but you're free to test lower