name: RCD-plugin
version: '${project.version}'
main: org.oreo.rcdplugin.RCD_plugin
api-version: '1.20'

commands:

  device:
    description: Debug commands for objects
    usage: /<command>
    aliases: [device]